name: Analyse Code

on:
  schedule:
    - cron: 0 0 * * 0

permissions:
  contents: read

jobs:
  analyse-code:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: Analysing Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initializing CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          queries: +security-extended

      - name: Auto Build
        uses: github/codeql-action/autobuild@v3

      - name: Performing CodeQL Analysis
        uses: github/codeql-action/analyze@v3
