name: Auto Release

on:
  push:
    branches:
      - main
jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.RELEASE_TOKEN }}
          pull-request-title-pattern: 'chore(release): bump version to ${version}'
          component: nestjs
          release-as: 2.1.0
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "style",
                "section": "Styles"
              },
              {
                "type": "refactor",
                "section": "Code Refactoring"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "test",
                "section": "Tests"
              },
              {
                "type": "ci",
                "section": "Continuous Integration"
              },
              {
                "type": "chore",
                "section": "Chores"
              },
              {
                "type": "docs",
                "section": "Documentation"
              }
            ]
