name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Creating Pull Request
        uses: google-github-actions/release-please-action@v3
        with:
          changelog-types: |
            [
              {
                "type": "feat",
                "section": "Features"
              },
              {
                "type": "fix",
                "section": "Bug Fixes"
              },
              {
                "type": "style",
                "section": "Styles"
              },
              {
                "type": "refactor",
                "section": "Code Refactoring"
              },
              {
                "type": "perf",
                "section": "Performance Improvements"
              },
              {
                "type": "test",
                "section": "Tests"
              },
              {
                "type": "ci",
                "section": "Continuous Integration"
              },
              {
                "type": "chore",
                "section": "Chores"
              },
              {
                "type": "docs",
                "section": "Documentation"
              }
            ]
          component: nestjs-boilerplate
          default-branch: main
          pull-request-title-pattern: 'chore${scope}: bump version to ${version}'
          release-type: node
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
